
info:
  #imgpath: "C:/Users/lv/Desktop/imglist/"
  imgpath: "/usr/local/imgs/"
  imgget: "http://182.92.64.54:7654/image/"
  #imgget: "http://192.168.50.108:7654/image/"

myqueque: boot-activemq-queue
server:
  port: 7654

spring:
#  activemq:
#    broker-url: nio://127.0.0.1:61608
#    user: admin
#    password: admin
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  datasource:
#   数据源基本配置

    driver-class-name: com.mysql.jdbc.Driver

    #url: jdbc:mysql://182.92.64.54:3306/weddingcar?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=utf8
    url: jdbc:mysql://182.92.64.54:3306/weddingcar?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: HUNche!@12

    #password: 123456
 #   url: jdbc:mysql://127.0.0.1:3306/outport?serverTimezone=GMT%2B8&useSSL=false
 #   username: root
  #  assword: root123456
    type: com.alibaba.druid.pool.DruidDataSource
#   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
#   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  mvc:
      static-path-pattern: /image/**
  resources:
      static-locations: "/usr/local/imgs/"
      #static-locations: "C:/Users/lv/Desktop/imglist/"
  jms:
    pub-sub-domain: false
  redis:
    host: 182.92.64.54
    port: 6379
    timeout: 3000
    jedis:
      pool:
        max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 10
      # 连接超时时间（毫秒）





# 配置mybatis-plus
mybatis-plus:
  # 配置扫描xml
  mapper-locations:
    - classpath:mapper/api/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.zjh.proj
  global-config:
      #刷新mapper 调试神器
      db-config:
        #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
        id-type: id_worker
        #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
        field-strategy: not_empty
        #驼峰下划线转换
        column-underline: true
        #数据库大写下划线转换
        #capital-mode: true
        #逻辑删除配置
        logic-delete-value: 0
        logic-not-delete-value: 1
        db-type: h2
      refresh: true
        #自定义填充策略接口实现
        #meta-object-handler: com.baomidou.springboot.xxx
        #自定义SQL注入器
        #sql-injector: com.baomidou.springboot.xxx
  configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false
      #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql
